### ISSUE TITLE
feat: set project development environment

### ISSUE THREAD

**Issue by poiu694** [mash-up-kr/VitaminC_Web#2]
## Description

프로젝트 진행을 위한 기본 개발 환경 세팅을 진행합니다.

## Task

- [x] Next.js 14
- [x] Typescript
- [x] tailwind
- [x] tanstack-query
- [x] eslint
- [x] prettier
- [x] ci/cd
- [x] vitest
- [x] storybook
- [x] ...

**Comment by 2-NOW** [comment]
테스트 세팅까지.. 멋져요
